# Generated by Django 5.2.8 on 2025-12-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了日時'),
        ),
    ]
