# Generated by Django 5.2.8 on 2025-12-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='retrieval_meta',
            field=models.JSONField(blank=True, help_text='検索スコアやフォールバック状況等をJSONで保存', null=True, verbose_name='検索メタデータ'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='routing_meta',
            field=models.JSONField(blank=True, help_text='LLMルーティング結果(is_business等)をJSONで保存', null=True, verbose_name='ルーティングメタデータ'),
        ),
    ]
