# Generated by Django 5.2.8 on 2025-12-24 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_code'),
        ('chat', '0003_chatmessage_retrieval_meta_chatmessage_routing_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='answer_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='accounts.department', verbose_name='最後に回答した部門'),
        ),
    ]
