# Generated by Django 5.2.8 on 2025-12-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_answer_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='citations',
            field=models.JSONField(blank=True, default=list, help_text='RAGが参照したドキュメント情報(document単位で集約)', verbose_name='出典(citations)'),
        ),
    ]
