# Generated by Django 5.2.8 on 2026-01-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='評価日時'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'GOOD'), (-1, 'BAD')], db_index=True, help_text='1=GOOD, -1=BAD, null=未評価', null=True, verbose_name='評価'),
        ),
    ]
