# Generated by Django 5.2.8 on 2025-12-13 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='部門コードは小文字英数字とアンダースコア(_)のみ使用できます。', regex='^[a-z0-9_]+$')], verbose_name='部門コード'),
        ),
    ]
