# Generated by Django 5.2.8 on 2025-12-13 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='部門コードは小文字英数字とアンダースコア(_)のみ使用できます。', regex='^[a-z0-9_]+$')], verbose_name='部門コード'),
        ),
    ]
