# Generated by Django 5.2.8 on 2025-12-01 22:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル(アップロード時のファイル名)')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイルパス')),
                ('num_page', models.IntegerField(blank=True, null=True, verbose_name='ページ数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.department', verbose_name='部門')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='アップロードユーザ')),
            ],
            options={
                'verbose_name': 'ドキュメント',
                'verbose_name_plural': 'ドキュメント',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(verbose_name='チャンク番号')),
                ('page', models.IntegerField(blank=True, null=True, verbose_name='元ページ番号')),
                ('content', models.TextField(verbose_name='テキスト')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='埋め込みベクトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document', verbose_name='ドキュメント')),
            ],
            options={
                'verbose_name': 'チャンク',
                'verbose_name_plural': 'チャンク',
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='documents_c_documen_0e3b68_idx')],
            },
        ),
    ]
