# Generated by Django 5.2.8 on 2025-12-19 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_code'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'アップロード'), ('DELETE', '削除'), ('REINDEX', '再インデックス')], max_length=20, verbose_name='操作')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失敗')], default='SUCCESS', max_length=10, verbose_name='結果')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='メッセージ')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザ')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.department', verbose_name='部門')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document', verbose_name='対象ドキュメント')),
            ],
            options={
                'verbose_name': '操作ログ',
                'verbose_name_plural': '操作ログ',
                'indexes': [models.Index(fields=['created_at'], name='documents_a_created_87bc41_idx'), models.Index(fields=['action', 'created_at'], name='documents_a_action_a45e22_idx'), models.Index(fields=['department', 'created_at'], name='documents_a_departm_397023_idx'), models.Index(fields=['document', 'created_at'], name='documents_a_documen_bf7c7d_idx')],
            },
        ),
    ]
