# Generated by Django 5.2.8 on 2025-12-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'アップロード'), ('DELETE', '削除'), ('REINDEX', '再インデックス'), ('REINDEX_ALL', '全件再インデックス')], max_length=20, verbose_name='操作'),
        ),
    ]
