# Generated by Django 5.2.8 on 2025-12-28 00:33

from django.db import migrations
from django.contrib.postgres.indexes import GinIndex

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_auditlog_action'),
    ]

    operations = [
        # pg_trgm extension（DB全体への機能追加）
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),

        # Chunk.content に trigram 用 GIN index
        migrations.AddIndex(
            model_name="chunk",
            index=GinIndex(
                name="chunk_content_trgm_gin",
                fields=["content"],
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
